// <auto-generated />
using System;
using EBOOK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EBOOK.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215100229_AddCoursesSeed")]
    partial class AddCoursesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("EBOOK.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Terminales S-2025",
                            Year = 2025
                        });
                });

            modelBuilder.Entity("EBOOK.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 1,
                            Description = "Analyse et Algèbre.",
                            TeacherId = 1,
                            Title = "Mathématiques Avancées"
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 1,
                            Description = "Mécanique quantique et chimie organique.",
                            TeacherId = 1,
                            Title = "Physique-Chimie"
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 1,
                            Description = "Algorithmique et programmation C#.",
                            TeacherId = 1,
                            Title = "Informatique"
                        },
                        new
                        {
                            Id = 4,
                            ClassroomId = 1,
                            Description = "Cellules, ADN et génétique.",
                            TeacherId = 1,
                            Title = "Biologie"
                        });
                });

            modelBuilder.Entity("EBOOK.Models.NotebookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseId");

                    b.ToTable("NotebookEntries");
                });

            modelBuilder.Entity("EBOOK.Models.Presence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Presences");
                });

            modelBuilder.Entity("EBOOK.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 1,
                            DateOfBirth = new DateTime(2007, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            LastName = "Mang"
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 1,
                            DateOfBirth = new DateTime(2006, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bruno",
                            LastName = "Leukeng"
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 1,
                            DateOfBirth = new DateTime(2007, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chloé",
                            LastName = "Pagou"
                        });
                });

            modelBuilder.Entity("EBOOK.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sophie.dubois@ebook.edu",
                            FirstName = "Sophie",
                            LastName = "Dubois",
                            PasswordHash = ""
                        },
                        new
                        {
                            Id = 2,
                            Email = "marc.durand@ebook.edu",
                            FirstName = "Marc",
                            LastName = "Durand",
                            PasswordHash = ""
                        });
                });

            modelBuilder.Entity("EBOOK.Models.Course", b =>
                {
                    b.HasOne("EBOOK.Models.Classroom", "Classroom")
                        .WithMany("Courses")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBOOK.Models.User", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EBOOK.Models.NotebookEntry", b =>
                {
                    b.HasOne("EBOOK.Models.User", "Author")
                        .WithMany("NotebookEntries")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBOOK.Models.Course", "Course")
                        .WithMany("Entries")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EBOOK.Models.Presence", b =>
                {
                    b.HasOne("EBOOK.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EBOOK.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EBOOK.Models.Student", b =>
                {
                    b.HasOne("EBOOK.Models.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("EBOOK.Models.Classroom", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EBOOK.Models.Course", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("EBOOK.Models.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("NotebookEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
